// import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */
export const users = [
  {
    _id: "asassdafdgdk",
    firstName: "Vinit",
    lastName: "Kanse",
    username: "vinit@ceo.com",
    password: "12345678",
    createdAt: "2022-01-25T10:38:12+05:30",
    updatedAt: "2022-05-17T10:33:36+05:30",
    userHandler: "vinc3nati",
    pic: "https://res.cloudinary.com/randomwave45/image/upload/v1654258967/20170224152725_IMG_0843_eidmuv.jpg",
    link: "https://vinit-kanse.netlify.app",
    bio: "Software Developer",
    followers: [
      {
        _id: "asassddsd243434",
        firstName: "Isha",
        lastName: "Dey",
        username: "ishadey@gmail.com",
        password: "1234abcd",
        createdAt: "2022-03-21T10:12:12+05:30",
        updatedAt: "2022-05-16T18:11:07+05:30",
        userHandler: "isha76",
        pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
        link: "https://isha.netlify.app",
        bio: "Digital Marketing expert",
        followers: [
          {
            _id: "asassdafdgdk",
            firstName: "Vinit",
            lastName: "Kanse",
            username: "vinit@ceo.com",
            password: "12345678",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-17T10:33:36+05:30",
            userHandler: "vinc3nati",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1654258967/20170224152725_IMG_0843_eidmuv.jpg",
            link: "https://vinit-kanse.netlify.app",
            bio: "Software Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "1",
          },
        ],
        following: [],
        bookmarks: [],
        id: "2",
      },
    ],
  },
  {
    _id: "asassddsd243434",
    firstName: "Jignesh",
    lastName: "Ghosh",
    username: "jiggighosh@gmail.com",
    password: "1234abcd",
    createdAt: "2022-03-21T10:12:12+05:30",
    updatedAt: "2022-05-17T11:07:58+05:30",
    userHandler: "jiggi",
    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
    link: "https://jiggi.netlify.app",
    bio: "Social Media Influencer",
    followers: [
      {
        _id: "asassdafdgdk",
        firstName: "Chetan",
        lastName: "Patel",
        username: "chetan@gmail.com",
        password: "1234abcd",
        createdAt: "2022-01-25T10:38:12+05:30",
        updatedAt: "2022-05-14T18:08:40+05:30",
        userHandler: "chetan",
        pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
        link: "https://chetanspage.netlify.app",
        bio: "Aspiring Software Developer",
        followers: [],
        following: [],
        bookmarks: [],
        id: "1",
      },
      {
        _id: "asassddfd232fgfg323",
        firstName: "Vijay",
        lastName: "Kamle",
        username: "vijaykamle@gmail.com",
        password: "1234asdf",
        createdAt: "2022-04-09T09:30:12+05:30",
        updatedAt: "2022-05-16T18:13:02+05:30",
        userHandler: "subhashdugar",
        pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650022195/saitama_isaxm6.jpg",
        link: "https://subhasdugar.netlify.app",
        bio: "Web Developer",
        followers: [
          {
            _id: "asassddsd243434",
            firstName: "Jignesh",
            lastName: "Ghosh",
            username: "jiggighosh@gmail.com",
            password: "1234abcd",
            createdAt: "2022-03-21T10:12:12+05:30",
            updatedAt: "2022-05-16T18:12:59+05:30",
            userHandler: "jiggi",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
            link: "https://jiggi.netlify.app",
            bio: "Social Media Influencer",
            followers: [
              {
                _id: "asassdafdgdk",
                firstName: "Chetan",
                lastName: "Patel",
                username: "chetan@gmail.com",
                password: "1234abcd",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-14T18:08:40+05:30",
                userHandler: "chetan",
                pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
                link: "https://chetanspage.netlify.app",
                bio: "Aspiring Software Developer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "1",
              },
            ],
            following: [
              {
                _id: "asassdafdgdk",
                firstName: "Chetan",
                lastName: "Patel",
                username: "chetan@gmail.com",
                password: "1234abcd",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-16T18:11:33+05:30",
                userHandler: "chetan",
                pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
                link: "https://chetanspage.netlify.app",
                bio: "Aspiring Software Developer",
                followers: [],
                following: [
                  {
                    _id: "asassddsd243434",
                    firstName: "Jignesh",
                    lastName: "Ghosh",
                    username: "jiggighosh@gmail.com",
                    password: "1234abcd",
                    createdAt: "2022-03-21T10:12:12+05:30",
                    updatedAt: "2022-05-14T18:10:33+05:30",
                    userHandler: "jiggi",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                    link: "https://jiggi.netlify.app",
                    bio: "Social Media Influencer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "2",
                  },
                  {
                    _id: "asassddfdsfdgsd32323",
                    firstName: "Jyoti",
                    lastName: "Kashti",
                    username: "jyotikashti@gmail.com",
                    password: "1234asdf",
                    createdAt: "2022-05-12T08:30:12+05:30",
                    updatedAt: "2022-05-14T18:11:48+05:30",
                    userHandler: "jyotiKashti",
                    pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/uchicha_crest_ngetfr.jpg",
                    link: "https://jyotikashti.netlify.app",
                    bio: "Web Designer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "3",
                  },
                ],
                bookmarks: [],
                id: "1",
              },
            ],
            bookmarks: [],
            id: "2",
          },
        ],
        following: [],
        bookmarks: [],
        id: "4",
      },
      {
        _id: "asassddfdsfdgsd32323",
        firstName: "Jyoti",
        lastName: "Kashti",
        username: "jyotikashti@gmail.com",
        password: "1234asdf",
        createdAt: "2022-05-12T08:30:12+05:30",
        updatedAt: "2022-05-17T11:05:59+05:30",
        userHandler: "jyotiKashti",
        pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/uchicha_crest_ngetfr.jpg",
        link: "https://jyotikashti.netlify.app",
        bio: "Web Designer",
        followers: [
          {
            _id: "asassdafdgdk",
            firstName: "Chetan",
            lastName: "Patel",
            username: "chetan@gmail.com",
            password: "1234abcd",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-16T18:11:07+05:30",
            userHandler: "chetan",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
            link: "https://chetanspage.netlify.app",
            bio: "Aspiring Software Developer",
            followers: [],
            following: [
              {
                _id: "asassddsd243434",
                firstName: "Jignesh",
                lastName: "Ghosh",
                username: "jiggighosh@gmail.com",
                password: "1234abcd",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-14T18:10:33+05:30",
                userHandler: "jiggi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://jiggi.netlify.app",
                bio: "Social Media Influencer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "2",
              },
            ],
            bookmarks: [],
            id: "1",
          },
          {
            _id: "asassddsd243434",
            firstName: "Jignesh",
            lastName: "Ghosh",
            username: "jiggighosh@gmail.com",
            password: "1234abcd",
            createdAt: "2022-03-21T10:12:12+05:30",
            updatedAt: "2022-05-17T10:24:05+05:30",
            userHandler: "jiggi",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
            link: "https://jiggi.netlify.app",
            bio: "Social Media Influencer",
            followers: [
              {
                _id: "asassdafdgdk",
                firstName: "Chetan",
                lastName: "Patel",
                username: "chetan@gmail.com",
                password: "1234abcd",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-14T18:08:40+05:30",
                userHandler: "chetan",
                pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
                link: "https://chetanspage.netlify.app",
                bio: "Aspiring Software Developer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "1",
              },
            ],
            following: [
              {
                _id: "asassdafdgdk",
                firstName: "Chetan",
                lastName: "Patel",
                username: "chetan@gmail.com",
                password: "1234abcd",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-16T18:11:33+05:30",
                userHandler: "chetan",
                pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
                link: "https://chetanspage.netlify.app",
                bio: "Aspiring Software Developer",
                followers: [],
                following: [
                  {
                    _id: "asassddsd243434",
                    firstName: "Jignesh",
                    lastName: "Ghosh",
                    username: "jiggighosh@gmail.com",
                    password: "1234abcd",
                    createdAt: "2022-03-21T10:12:12+05:30",
                    updatedAt: "2022-05-14T18:10:33+05:30",
                    userHandler: "jiggi",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                    link: "https://jiggi.netlify.app",
                    bio: "Social Media Influencer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "2",
                  },
                  {
                    _id: "asassddfdsfdgsd32323",
                    firstName: "Jyoti",
                    lastName: "Kashti",
                    username: "jyotikashti@gmail.com",
                    password: "1234asdf",
                    createdAt: "2022-05-12T08:30:12+05:30",
                    updatedAt: "2022-05-14T18:11:48+05:30",
                    userHandler: "jyotiKashti",
                    pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/uchicha_crest_ngetfr.jpg",
                    link: "https://jyotikashti.netlify.app",
                    bio: "Web Designer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "3",
                  },
                ],
                bookmarks: [],
                id: "1",
              },
              {
                _id: "asassddfd232fgfg323",
                firstName: "Vijay",
                lastName: "Kamle",
                username: "vijaykamle@gmail.com",
                password: "1234asdf",
                createdAt: "2022-04-09T09:30:12+05:30",
                updatedAt: "2022-05-14T18:12:29+05:30",
                userHandler: "subhashdugar",
                pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650022195/saitama_isaxm6.jpg",
                link: "https://subhasdugar.netlify.app",
                bio: "Web Developer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "4",
              },
              {
                _id: "asassddfd232fg23ssfdf",
                firstName: "Mohak",
                lastName: "Seth",
                username: "seth.mohak@gmail.com",
                password: "1234asdf",
                createdAt: "2022-02-10T09:30:12+05:30",
                updatedAt: "2022-05-16T18:11:01+05:30",
                userHandler: "seth.mohak",
                pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650022195/one_piece_2_jcjkvz.jpg",
                link: "https://seth.mohak.netlify.app",
                bio: "Mobile Developer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "5",
              },
            ],
            bookmarks: [],
            id: "2",
          },
        ],
        following: [
          {
            _id: "asassdafdgdk",
            firstName: "Chetan",
            lastName: "Patel",
            username: "chetan@gmail.com",
            password: "1234abcd",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-16T18:12:59+05:30",
            userHandler: "chetan",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
            link: "https://chetanspage.netlify.app",
            bio: "Aspiring Software Developer",
            followers: [
              {
                _id: "asassddsd243434",
                firstName: "Jignesh",
                lastName: "Ghosh",
                username: "jiggighosh@gmail.com",
                password: "1234abcd",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-16T18:11:07+05:30",
                userHandler: "jiggi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://jiggi.netlify.app",
                bio: "Social Media Influencer",
                followers: [
                  {
                    _id: "asassdafdgdk",
                    firstName: "Chetan",
                    lastName: "Patel",
                    username: "chetan@gmail.com",
                    password: "1234abcd",
                    createdAt: "2022-01-25T10:38:12+05:30",
                    updatedAt: "2022-05-14T18:08:40+05:30",
                    userHandler: "chetan",
                    pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
                    link: "https://chetanspage.netlify.app",
                    bio: "Aspiring Software Developer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "1",
                  },
                ],
                following: [],
                bookmarks: [],
                id: "2",
              },
            ],
            following: [
              {
                _id: "asassddsd243434",
                firstName: "Jignesh",
                lastName: "Ghosh",
                username: "jiggighosh@gmail.com",
                password: "1234abcd",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-14T18:10:33+05:30",
                userHandler: "jiggi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://jiggi.netlify.app",
                bio: "Social Media Influencer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "2",
              },
              {
                _id: "asassddfdsfdgsd32323",
                firstName: "Jyoti",
                lastName: "Kashti",
                username: "jyotikashti@gmail.com",
                password: "1234asdf",
                createdAt: "2022-05-12T08:30:12+05:30",
                updatedAt: "2022-05-14T18:11:48+05:30",
                userHandler: "jyotiKashti",
                pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/uchicha_crest_ngetfr.jpg",
                link: "https://jyotikashti.netlify.app",
                bio: "Web Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "3",
              },
            ],
            bookmarks: [],
            id: "1",
          },
        ],
        bookmarks: [],
        id: "3",
      },
    ],
    following: [
      {
        _id: "asassdafdgdk",
        firstName: "Chetan",
        lastName: "Patel",
        username: "chetan@gmail.com",
        password: "1234abcd",
        createdAt: "2022-01-25T10:38:12+05:30",
        updatedAt: "2022-05-16T18:11:33+05:30",
        userHandler: "chetan",
        pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
        link: "https://chetanspage.netlify.app",
        bio: "Aspiring Software Developer",
        followers: [],
        following: [
          {
            _id: "asassddsd243434",
            firstName: "Jignesh",
            lastName: "Ghosh",
            username: "jiggighosh@gmail.com",
            password: "1234abcd",
            createdAt: "2022-03-21T10:12:12+05:30",
            updatedAt: "2022-05-14T18:10:33+05:30",
            userHandler: "jiggi",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
            link: "https://jiggi.netlify.app",
            bio: "Social Media Influencer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "2",
          },
          {
            _id: "asassddfdsfdgsd32323",
            firstName: "Jyoti",
            lastName: "Kashti",
            username: "jyotikashti@gmail.com",
            password: "1234asdf",
            createdAt: "2022-05-12T08:30:12+05:30",
            updatedAt: "2022-05-14T18:11:48+05:30",
            userHandler: "jyotiKashti",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/uchicha_crest_ngetfr.jpg",
            link: "https://jyotikashti.netlify.app",
            bio: "Web Designer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "3",
          },
        ],
        bookmarks: [],
        id: "1",
      },
      {
        _id: "asassddfd232fgfg323",
        firstName: "Vijay",
        lastName: "Kamle",
        username: "vijaykamle@gmail.com",
        password: "1234asdf",
        createdAt: "2022-04-09T09:30:12+05:30",
        updatedAt: "2022-05-14T18:12:29+05:30",
        userHandler: "subhashdugar",
        pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650022195/saitama_isaxm6.jpg",
        link: "https://subhasdugar.netlify.app",
        bio: "Web Developer",
        followers: [],
        following: [],
        bookmarks: [],
        id: "4",
      },
      {
        _id: "asassddfd232fg23ssfdf",
        firstName: "Mohak",
        lastName: "Seth",
        username: "seth.mohak@gmail.com",
        password: "1234asdf",
        createdAt: "2022-02-10T09:30:12+05:30",
        updatedAt: "2022-05-16T18:11:01+05:30",
        userHandler: "seth.mohak",
        pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650022195/one_piece_2_jcjkvz.jpg",
        link: "https://seth.mohak.netlify.app",
        bio: "Mobile Developer",
        followers: [],
        following: [],
        bookmarks: [],
        id: "5",
      },
      {
        _id: "asassddfdsfdgsd32323",
        firstName: "Jyoti",
        lastName: "Kashti",
        username: "jyotikashti@gmail.com",
        password: "1234asdf",
        createdAt: "2022-05-12T08:30:12+05:30",
        updatedAt: "2022-05-16T18:14:29+05:30",
        userHandler: "jyotiKashti",
        pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/uchicha_crest_ngetfr.jpg",
        link: "https://jyotikashti.netlify.app",
        bio: "Web Designer",
        followers: [
          {
            _id: "asassdafdgdk",
            firstName: "Chetan",
            lastName: "Patel",
            username: "chetan@gmail.com",
            password: "1234abcd",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-16T18:11:07+05:30",
            userHandler: "chetan",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
            link: "https://chetanspage.netlify.app",
            bio: "Aspiring Software Developer",
            followers: [],
            following: [
              {
                _id: "asassddsd243434",
                firstName: "Jignesh",
                lastName: "Ghosh",
                username: "jiggighosh@gmail.com",
                password: "1234abcd",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-14T18:10:33+05:30",
                userHandler: "jiggi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://jiggi.netlify.app",
                bio: "Social Media Influencer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "2",
              },
            ],
            bookmarks: [],
            id: "1",
          },
        ],
        following: [
          {
            _id: "asassdafdgdk",
            firstName: "Chetan",
            lastName: "Patel",
            username: "chetan@gmail.com",
            password: "1234abcd",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-16T18:12:59+05:30",
            userHandler: "chetan",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
            link: "https://chetanspage.netlify.app",
            bio: "Aspiring Software Developer",
            followers: [
              {
                _id: "asassddsd243434",
                firstName: "Jignesh",
                lastName: "Ghosh",
                username: "jiggighosh@gmail.com",
                password: "1234abcd",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-16T18:11:07+05:30",
                userHandler: "jiggi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://jiggi.netlify.app",
                bio: "Social Media Influencer",
                followers: [
                  {
                    _id: "asassdafdgdk",
                    firstName: "Chetan",
                    lastName: "Patel",
                    username: "chetan@gmail.com",
                    password: "1234abcd",
                    createdAt: "2022-01-25T10:38:12+05:30",
                    updatedAt: "2022-05-14T18:08:40+05:30",
                    userHandler: "chetan",
                    pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
                    link: "https://chetanspage.netlify.app",
                    bio: "Aspiring Software Developer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "1",
                  },
                ],
                following: [],
                bookmarks: [],
                id: "2",
              },
            ],
            following: [
              {
                _id: "asassddsd243434",
                firstName: "Jignesh",
                lastName: "Ghosh",
                username: "jiggighosh@gmail.com",
                password: "1234abcd",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-14T18:10:33+05:30",
                userHandler: "jiggi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://jiggi.netlify.app",
                bio: "Social Media Influencer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "2",
              },
              {
                _id: "asassddfdsfdgsd32323",
                firstName: "Jyoti",
                lastName: "Kashti",
                username: "jyotikashti@gmail.com",
                password: "1234asdf",
                createdAt: "2022-05-12T08:30:12+05:30",
                updatedAt: "2022-05-14T18:11:48+05:30",
                userHandler: "jyotiKashti",
                pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/uchicha_crest_ngetfr.jpg",
                link: "https://jyotikashti.netlify.app",
                bio: "Web Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "3",
              },
            ],
            bookmarks: [],
            id: "1",
          },
        ],
        bookmarks: [],
        id: "3",
      },
    ],
    bookmarks: [],
    id: "2",
  },
  {
    _id: "asassddfdsfdgsd32323",
    firstName: "Jyoti",
    lastName: "Kashti",
    username: "jyotikashti@gmail.com",
    password: "1234asdf",
    createdAt: "2022-05-12T08:30:12+05:30",
    updatedAt: "2022-05-17T11:07:58+05:30",
    userHandler: "jyotiKashti",
    pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/uchicha_crest_ngetfr.jpg",
    link: "https://jyotikashti.netlify.app",
    bio: "Web Designer",
    followers: [
      {
        _id: "asassdafdgdk",
        firstName: "Chetan",
        lastName: "Patel",
        username: "chetan@gmail.com",
        password: "1234abcd",
        createdAt: "2022-01-25T10:38:12+05:30",
        updatedAt: "2022-05-16T18:11:07+05:30",
        userHandler: "chetan",
        pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
        link: "https://chetanspage.netlify.app",
        bio: "Aspiring Software Developer",
        followers: [],
        following: [
          {
            _id: "asassddsd243434",
            firstName: "Jignesh",
            lastName: "Ghosh",
            username: "jiggighosh@gmail.com",
            password: "1234abcd",
            createdAt: "2022-03-21T10:12:12+05:30",
            updatedAt: "2022-05-14T18:10:33+05:30",
            userHandler: "jiggi",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
            link: "https://jiggi.netlify.app",
            bio: "Social Media Influencer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "2",
          },
        ],
        bookmarks: [],
        id: "1",
      },
      {
        _id: "asassddsd243434",
        firstName: "Jignesh",
        lastName: "Ghosh",
        username: "jiggighosh@gmail.com",
        password: "1234abcd",
        createdAt: "2022-03-21T10:12:12+05:30",
        updatedAt: "2022-05-17T10:24:05+05:30",
        userHandler: "jiggi",
        pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
        link: "https://jiggi.netlify.app",
        bio: "Social Media Influencer",
        followers: [
          {
            _id: "asassdafdgdk",
            firstName: "Chetan",
            lastName: "Patel",
            username: "chetan@gmail.com",
            password: "1234abcd",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-14T18:08:40+05:30",
            userHandler: "chetan",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
            link: "https://chetanspage.netlify.app",
            bio: "Aspiring Software Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "1",
          },
        ],
        following: [
          {
            _id: "asassdafdgdk",
            firstName: "Chetan",
            lastName: "Patel",
            username: "chetan@gmail.com",
            password: "1234abcd",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-16T18:11:33+05:30",
            userHandler: "chetan",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
            link: "https://chetanspage.netlify.app",
            bio: "Aspiring Software Developer",
            followers: [],
            following: [
              {
                _id: "asassddsd243434",
                firstName: "Jignesh",
                lastName: "Ghosh",
                username: "jiggighosh@gmail.com",
                password: "1234abcd",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-14T18:10:33+05:30",
                userHandler: "jiggi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://jiggi.netlify.app",
                bio: "Social Media Influencer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "2",
              },
              {
                _id: "asassddfdsfdgsd32323",
                firstName: "Jyoti",
                lastName: "Kashti",
                username: "jyotikashti@gmail.com",
                password: "1234asdf",
                createdAt: "2022-05-12T08:30:12+05:30",
                updatedAt: "2022-05-14T18:11:48+05:30",
                userHandler: "jyotiKashti",
                pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/uchicha_crest_ngetfr.jpg",
                link: "https://jyotikashti.netlify.app",
                bio: "Web Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "3",
              },
            ],
            bookmarks: [],
            id: "1",
          },
          {
            _id: "asassddfd232fgfg323",
            firstName: "Vijay",
            lastName: "Kamle",
            username: "vijaykamle@gmail.com",
            password: "1234asdf",
            createdAt: "2022-04-09T09:30:12+05:30",
            updatedAt: "2022-05-14T18:12:29+05:30",
            userHandler: "subhashdugar",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650022195/saitama_isaxm6.jpg",
            link: "https://subhasdugar.netlify.app",
            bio: "Web Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "4",
          },
          {
            _id: "asassddfd232fg23ssfdf",
            firstName: "Mohak",
            lastName: "Seth",
            username: "seth.mohak@gmail.com",
            password: "1234asdf",
            createdAt: "2022-02-10T09:30:12+05:30",
            updatedAt: "2022-05-16T18:11:01+05:30",
            userHandler: "seth.mohak",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650022195/one_piece_2_jcjkvz.jpg",
            link: "https://seth.mohak.netlify.app",
            bio: "Mobile Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "5",
          },
        ],
        bookmarks: [],
        id: "2",
      },
    ],
    following: [
      {
        _id: "asassdafdgdk",
        firstName: "Chetan",
        lastName: "Patel",
        username: "chetan@gmail.com",
        password: "1234abcd",
        createdAt: "2022-01-25T10:38:12+05:30",
        updatedAt: "2022-05-16T18:12:59+05:30",
        userHandler: "chetan",
        pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
        link: "https://chetanspage.netlify.app",
        bio: "Aspiring Software Developer",
        followers: [
          {
            _id: "asassddsd243434",
            firstName: "Jignesh",
            lastName: "Ghosh",
            username: "jiggighosh@gmail.com",
            password: "1234abcd",
            createdAt: "2022-03-21T10:12:12+05:30",
            updatedAt: "2022-05-16T18:11:07+05:30",
            userHandler: "jiggi",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
            link: "https://jiggi.netlify.app",
            bio: "Social Media Influencer",
            followers: [
              {
                _id: "asassdafdgdk",
                firstName: "Chetan",
                lastName: "Patel",
                username: "chetan@gmail.com",
                password: "1234abcd",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-14T18:08:40+05:30",
                userHandler: "chetan",
                pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
                link: "https://chetanspage.netlify.app",
                bio: "Aspiring Software Developer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "1",
              },
            ],
            following: [],
            bookmarks: [],
            id: "2",
          },
        ],
        following: [
          {
            _id: "asassddsd243434",
            firstName: "Jignesh",
            lastName: "Ghosh",
            username: "jiggighosh@gmail.com",
            password: "1234abcd",
            createdAt: "2022-03-21T10:12:12+05:30",
            updatedAt: "2022-05-14T18:10:33+05:30",
            userHandler: "jiggi",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
            link: "https://jiggi.netlify.app",
            bio: "Social Media Influencer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "2",
          },
          {
            _id: "asassddfdsfdgsd32323",
            firstName: "Jyoti",
            lastName: "Kashti",
            username: "jyotikashti@gmail.com",
            password: "1234asdf",
            createdAt: "2022-05-12T08:30:12+05:30",
            updatedAt: "2022-05-14T18:11:48+05:30",
            userHandler: "jyotiKashti",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/uchicha_crest_ngetfr.jpg",
            link: "https://jyotikashti.netlify.app",
            bio: "Web Designer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "3",
          },
        ],
        bookmarks: [],
        id: "1",
      },
      {
        _id: "asassddsd243434",
        firstName: "Jignesh",
        lastName: "Ghosh",
        username: "jiggighosh@gmail.com",
        password: "1234abcd",
        createdAt: "2022-03-21T10:12:12+05:30",
        updatedAt: "2022-05-17T11:07:26+05:30",
        userHandler: "jiggi",
        pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
        link: "https://jiggi.netlify.app",
        bio: "Social Media Influencer",
        followers: [
          {
            _id: "asassdafdgdk",
            firstName: "Chetan",
            lastName: "Patel",
            username: "chetan@gmail.com",
            password: "1234abcd",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-14T18:08:40+05:30",
            userHandler: "chetan",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
            link: "https://chetanspage.netlify.app",
            bio: "Aspiring Software Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "1",
          },
          {
            _id: "asassddfd232fgfg323",
            firstName: "Vijay",
            lastName: "Kamle",
            username: "vijaykamle@gmail.com",
            password: "1234asdf",
            createdAt: "2022-04-09T09:30:12+05:30",
            updatedAt: "2022-05-16T18:13:02+05:30",
            userHandler: "subhashdugar",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650022195/saitama_isaxm6.jpg",
            link: "https://subhasdugar.netlify.app",
            bio: "Web Developer",
            followers: [
              {
                _id: "asassddsd243434",
                firstName: "Jignesh",
                lastName: "Ghosh",
                username: "jiggighosh@gmail.com",
                password: "1234abcd",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-16T18:12:59+05:30",
                userHandler: "jiggi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://jiggi.netlify.app",
                bio: "Social Media Influencer",
                followers: [
                  {
                    _id: "asassdafdgdk",
                    firstName: "Chetan",
                    lastName: "Patel",
                    username: "chetan@gmail.com",
                    password: "1234abcd",
                    createdAt: "2022-01-25T10:38:12+05:30",
                    updatedAt: "2022-05-14T18:08:40+05:30",
                    userHandler: "chetan",
                    pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
                    link: "https://chetanspage.netlify.app",
                    bio: "Aspiring Software Developer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "1",
                  },
                ],
                following: [
                  {
                    _id: "asassdafdgdk",
                    firstName: "Chetan",
                    lastName: "Patel",
                    username: "chetan@gmail.com",
                    password: "1234abcd",
                    createdAt: "2022-01-25T10:38:12+05:30",
                    updatedAt: "2022-05-16T18:11:33+05:30",
                    userHandler: "chetan",
                    pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
                    link: "https://chetanspage.netlify.app",
                    bio: "Aspiring Software Developer",
                    followers: [],
                    following: [
                      {
                        _id: "asassddsd243434",
                        firstName: "Jignesh",
                        lastName: "Ghosh",
                        username: "jiggighosh@gmail.com",
                        password: "1234abcd",
                        createdAt: "2022-03-21T10:12:12+05:30",
                        updatedAt: "2022-05-14T18:10:33+05:30",
                        userHandler: "jiggi",
                        pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                        link: "https://jiggi.netlify.app",
                        bio: "Social Media Influencer",
                        followers: [],
                        following: [],
                        bookmarks: [],
                        id: "2",
                      },
                      {
                        _id: "asassddfdsfdgsd32323",
                        firstName: "Jyoti",
                        lastName: "Kashti",
                        username: "jyotikashti@gmail.com",
                        password: "1234asdf",
                        createdAt: "2022-05-12T08:30:12+05:30",
                        updatedAt: "2022-05-14T18:11:48+05:30",
                        userHandler: "jyotiKashti",
                        pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/uchicha_crest_ngetfr.jpg",
                        link: "https://jyotikashti.netlify.app",
                        bio: "Web Designer",
                        followers: [],
                        following: [],
                        bookmarks: [],
                        id: "3",
                      },
                    ],
                    bookmarks: [],
                    id: "1",
                  },
                ],
                bookmarks: [],
                id: "2",
              },
            ],
            following: [],
            bookmarks: [],
            id: "4",
          },
        ],
        following: [
          {
            _id: "asassdafdgdk",
            firstName: "Chetan",
            lastName: "Patel",
            username: "chetan@gmail.com",
            password: "1234abcd",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-16T18:11:33+05:30",
            userHandler: "chetan",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
            link: "https://chetanspage.netlify.app",
            bio: "Aspiring Software Developer",
            followers: [],
            following: [
              {
                _id: "asassddsd243434",
                firstName: "Jignesh",
                lastName: "Ghosh",
                username: "jiggighosh@gmail.com",
                password: "1234abcd",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-14T18:10:33+05:30",
                userHandler: "jiggi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://jiggi.netlify.app",
                bio: "Social Media Influencer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "2",
              },
              {
                _id: "asassddfdsfdgsd32323",
                firstName: "Jyoti",
                lastName: "Kashti",
                username: "jyotikashti@gmail.com",
                password: "1234asdf",
                createdAt: "2022-05-12T08:30:12+05:30",
                updatedAt: "2022-05-14T18:11:48+05:30",
                userHandler: "jyotiKashti",
                pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/uchicha_crest_ngetfr.jpg",
                link: "https://jyotikashti.netlify.app",
                bio: "Web Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "3",
              },
            ],
            bookmarks: [],
            id: "1",
          },
          {
            _id: "asassddfd232fgfg323",
            firstName: "Vijay",
            lastName: "Kamle",
            username: "vijaykamle@gmail.com",
            password: "1234asdf",
            createdAt: "2022-04-09T09:30:12+05:30",
            updatedAt: "2022-05-14T18:12:29+05:30",
            userHandler: "subhashdugar",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650022195/saitama_isaxm6.jpg",
            link: "https://subhasdugar.netlify.app",
            bio: "Web Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "4",
          },
          {
            _id: "asassddfd232fg23ssfdf",
            firstName: "Mohak",
            lastName: "Seth",
            username: "seth.mohak@gmail.com",
            password: "1234asdf",
            createdAt: "2022-02-10T09:30:12+05:30",
            updatedAt: "2022-05-16T18:11:01+05:30",
            userHandler: "seth.mohak",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650022195/one_piece_2_jcjkvz.jpg",
            link: "https://seth.mohak.netlify.app",
            bio: "Mobile Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "5",
          },
          {
            _id: "asassddfdsfdgsd32323",
            firstName: "Jyoti",
            lastName: "Kashti",
            username: "jyotikashti@gmail.com",
            password: "1234asdf",
            createdAt: "2022-05-12T08:30:12+05:30",
            updatedAt: "2022-05-16T18:14:29+05:30",
            userHandler: "jyotiKashti",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/uchicha_crest_ngetfr.jpg",
            link: "https://jyotikashti.netlify.app",
            bio: "Web Designer",
            followers: [
              {
                _id: "asassdafdgdk",
                firstName: "Chetan",
                lastName: "Patel",
                username: "chetan@gmail.com",
                password: "1234abcd",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-16T18:11:07+05:30",
                userHandler: "chetan",
                pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
                link: "https://chetanspage.netlify.app",
                bio: "Aspiring Software Developer",
                followers: [],
                following: [
                  {
                    _id: "asassddsd243434",
                    firstName: "Jignesh",
                    lastName: "Ghosh",
                    username: "jiggighosh@gmail.com",
                    password: "1234abcd",
                    createdAt: "2022-03-21T10:12:12+05:30",
                    updatedAt: "2022-05-14T18:10:33+05:30",
                    userHandler: "jiggi",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                    link: "https://jiggi.netlify.app",
                    bio: "Social Media Influencer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "2",
                  },
                ],
                bookmarks: [],
                id: "1",
              },
            ],
            following: [
              {
                _id: "asassdafdgdk",
                firstName: "Chetan",
                lastName: "Patel",
                username: "chetan@gmail.com",
                password: "1234abcd",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-16T18:12:59+05:30",
                userHandler: "chetan",
                pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
                link: "https://chetanspage.netlify.app",
                bio: "Aspiring Software Developer",
                followers: [
                  {
                    _id: "asassddsd243434",
                    firstName: "Jignesh",
                    lastName: "Ghosh",
                    username: "jiggighosh@gmail.com",
                    password: "1234abcd",
                    createdAt: "2022-03-21T10:12:12+05:30",
                    updatedAt: "2022-05-16T18:11:07+05:30",
                    userHandler: "jiggi",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                    link: "https://jiggi.netlify.app",
                    bio: "Social Media Influencer",
                    followers: [
                      {
                        _id: "asassdafdgdk",
                        firstName: "Chetan",
                        lastName: "Patel",
                        username: "chetan@gmail.com",
                        password: "1234abcd",
                        createdAt: "2022-01-25T10:38:12+05:30",
                        updatedAt: "2022-05-14T18:08:40+05:30",
                        userHandler: "chetan",
                        pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
                        link: "https://chetanspage.netlify.app",
                        bio: "Aspiring Software Developer",
                        followers: [],
                        following: [],
                        bookmarks: [],
                        id: "1",
                      },
                    ],
                    following: [],
                    bookmarks: [],
                    id: "2",
                  },
                ],
                following: [
                  {
                    _id: "asassddsd243434",
                    firstName: "Jignesh",
                    lastName: "Ghosh",
                    username: "jiggighosh@gmail.com",
                    password: "1234abcd",
                    createdAt: "2022-03-21T10:12:12+05:30",
                    updatedAt: "2022-05-14T18:10:33+05:30",
                    userHandler: "jiggi",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                    link: "https://jiggi.netlify.app",
                    bio: "Social Media Influencer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "2",
                  },
                  {
                    _id: "asassddfdsfdgsd32323",
                    firstName: "Jyoti",
                    lastName: "Kashti",
                    username: "jyotikashti@gmail.com",
                    password: "1234asdf",
                    createdAt: "2022-05-12T08:30:12+05:30",
                    updatedAt: "2022-05-14T18:11:48+05:30",
                    userHandler: "jyotiKashti",
                    pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/uchicha_crest_ngetfr.jpg",
                    link: "https://jyotikashti.netlify.app",
                    bio: "Web Designer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "3",
                  },
                ],
                bookmarks: [],
                id: "1",
              },
            ],
            bookmarks: [],
            id: "3",
          },
        ],
        bookmarks: [],
        id: "2",
      },
    ],
    bookmarks: [],
    id: "3",
  },
  {
    _id: "asassddfd232fgfg323",
    firstName: "Vijay",
    lastName: "Kamle",
    username: "vijaykamle@gmail.com",
    password: "1234asdf",
    createdAt: "2022-04-09T09:30:12+05:30",
    updatedAt: "2022-05-17T11:07:27+05:30",
    userHandler: "subhashdugar",
    pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650022195/saitama_isaxm6.jpg",
    link: "https://subhasdugar.netlify.app",
    bio: "Web Developer",
    followers: [
      {
        _id: "asassddsd243434",
        firstName: "Jignesh",
        lastName: "Ghosh",
        username: "jiggighosh@gmail.com",
        password: "1234abcd",
        createdAt: "2022-03-21T10:12:12+05:30",
        updatedAt: "2022-05-16T18:12:59+05:30",
        userHandler: "jiggi",
        pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
        link: "https://jiggi.netlify.app",
        bio: "Social Media Influencer",
        followers: [
          {
            _id: "asassdafdgdk",
            firstName: "Chetan",
            lastName: "Patel",
            username: "chetan@gmail.com",
            password: "1234abcd",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-14T18:08:40+05:30",
            userHandler: "chetan",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
            link: "https://chetanspage.netlify.app",
            bio: "Aspiring Software Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "1",
          },
        ],
        following: [
          {
            _id: "asassdafdgdk",
            firstName: "Chetan",
            lastName: "Patel",
            username: "chetan@gmail.com",
            password: "1234abcd",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-16T18:11:33+05:30",
            userHandler: "chetan",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
            link: "https://chetanspage.netlify.app",
            bio: "Aspiring Software Developer",
            followers: [],
            following: [
              {
                _id: "asassddsd243434",
                firstName: "Jignesh",
                lastName: "Ghosh",
                username: "jiggighosh@gmail.com",
                password: "1234abcd",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-14T18:10:33+05:30",
                userHandler: "jiggi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://jiggi.netlify.app",
                bio: "Social Media Influencer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "2",
              },
              {
                _id: "asassddfdsfdgsd32323",
                firstName: "Jyoti",
                lastName: "Kashti",
                username: "jyotikashti@gmail.com",
                password: "1234asdf",
                createdAt: "2022-05-12T08:30:12+05:30",
                updatedAt: "2022-05-14T18:11:48+05:30",
                userHandler: "jyotiKashti",
                pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/uchicha_crest_ngetfr.jpg",
                link: "https://jyotikashti.netlify.app",
                bio: "Web Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "3",
              },
            ],
            bookmarks: [],
            id: "1",
          },
        ],
        bookmarks: [],
        id: "2",
      },
    ],
    following: [
      {
        _id: "asassddsd243434",
        firstName: "Jignesh",
        lastName: "Ghosh",
        username: "jiggighosh@gmail.com",
        password: "1234abcd",
        createdAt: "2022-03-21T10:12:12+05:30",
        updatedAt: "2022-05-17T11:05:59+05:30",
        userHandler: "jiggi",
        pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
        link: "https://jiggi.netlify.app",
        bio: "Social Media Influencer",
        followers: [
          {
            _id: "asassdafdgdk",
            firstName: "Chetan",
            lastName: "Patel",
            username: "chetan@gmail.com",
            password: "1234abcd",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-14T18:08:40+05:30",
            userHandler: "chetan",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
            link: "https://chetanspage.netlify.app",
            bio: "Aspiring Software Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "1",
          },
        ],
        following: [
          {
            _id: "asassdafdgdk",
            firstName: "Chetan",
            lastName: "Patel",
            username: "chetan@gmail.com",
            password: "1234abcd",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-16T18:11:33+05:30",
            userHandler: "chetan",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
            link: "https://chetanspage.netlify.app",
            bio: "Aspiring Software Developer",
            followers: [],
            following: [
              {
                _id: "asassddsd243434",
                firstName: "Jignesh",
                lastName: "Ghosh",
                username: "jiggighosh@gmail.com",
                password: "1234abcd",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-14T18:10:33+05:30",
                userHandler: "jiggi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://jiggi.netlify.app",
                bio: "Social Media Influencer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "2",
              },
              {
                _id: "asassddfdsfdgsd32323",
                firstName: "Jyoti",
                lastName: "Kashti",
                username: "jyotikashti@gmail.com",
                password: "1234asdf",
                createdAt: "2022-05-12T08:30:12+05:30",
                updatedAt: "2022-05-14T18:11:48+05:30",
                userHandler: "jyotiKashti",
                pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/uchicha_crest_ngetfr.jpg",
                link: "https://jyotikashti.netlify.app",
                bio: "Web Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "3",
              },
            ],
            bookmarks: [],
            id: "1",
          },
          {
            _id: "asassddfd232fgfg323",
            firstName: "Vijay",
            lastName: "Kamle",
            username: "vijaykamle@gmail.com",
            password: "1234asdf",
            createdAt: "2022-04-09T09:30:12+05:30",
            updatedAt: "2022-05-14T18:12:29+05:30",
            userHandler: "subhashdugar",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650022195/saitama_isaxm6.jpg",
            link: "https://subhasdugar.netlify.app",
            bio: "Web Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "4",
          },
          {
            _id: "asassddfd232fg23ssfdf",
            firstName: "Mohak",
            lastName: "Seth",
            username: "seth.mohak@gmail.com",
            password: "1234asdf",
            createdAt: "2022-02-10T09:30:12+05:30",
            updatedAt: "2022-05-16T18:11:01+05:30",
            userHandler: "seth.mohak",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650022195/one_piece_2_jcjkvz.jpg",
            link: "https://seth.mohak.netlify.app",
            bio: "Mobile Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "5",
          },
          {
            _id: "asassddfdsfdgsd32323",
            firstName: "Jyoti",
            lastName: "Kashti",
            username: "jyotikashti@gmail.com",
            password: "1234asdf",
            createdAt: "2022-05-12T08:30:12+05:30",
            updatedAt: "2022-05-16T18:14:29+05:30",
            userHandler: "jyotiKashti",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/uchicha_crest_ngetfr.jpg",
            link: "https://jyotikashti.netlify.app",
            bio: "Web Designer",
            followers: [
              {
                _id: "asassdafdgdk",
                firstName: "Chetan",
                lastName: "Patel",
                username: "chetan@gmail.com",
                password: "1234abcd",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-16T18:11:07+05:30",
                userHandler: "chetan",
                pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
                link: "https://chetanspage.netlify.app",
                bio: "Aspiring Software Developer",
                followers: [],
                following: [
                  {
                    _id: "asassddsd243434",
                    firstName: "Jignesh",
                    lastName: "Ghosh",
                    username: "jiggighosh@gmail.com",
                    password: "1234abcd",
                    createdAt: "2022-03-21T10:12:12+05:30",
                    updatedAt: "2022-05-14T18:10:33+05:30",
                    userHandler: "jiggi",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                    link: "https://jiggi.netlify.app",
                    bio: "Social Media Influencer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "2",
                  },
                ],
                bookmarks: [],
                id: "1",
              },
            ],
            following: [
              {
                _id: "asassdafdgdk",
                firstName: "Chetan",
                lastName: "Patel",
                username: "chetan@gmail.com",
                password: "1234abcd",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-16T18:12:59+05:30",
                userHandler: "chetan",
                pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
                link: "https://chetanspage.netlify.app",
                bio: "Aspiring Software Developer",
                followers: [
                  {
                    _id: "asassddsd243434",
                    firstName: "Jignesh",
                    lastName: "Ghosh",
                    username: "jiggighosh@gmail.com",
                    password: "1234abcd",
                    createdAt: "2022-03-21T10:12:12+05:30",
                    updatedAt: "2022-05-16T18:11:07+05:30",
                    userHandler: "jiggi",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                    link: "https://jiggi.netlify.app",
                    bio: "Social Media Influencer",
                    followers: [
                      {
                        _id: "asassdafdgdk",
                        firstName: "Chetan",
                        lastName: "Patel",
                        username: "chetan@gmail.com",
                        password: "1234abcd",
                        createdAt: "2022-01-25T10:38:12+05:30",
                        updatedAt: "2022-05-14T18:08:40+05:30",
                        userHandler: "chetan",
                        pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
                        link: "https://chetanspage.netlify.app",
                        bio: "Aspiring Software Developer",
                        followers: [],
                        following: [],
                        bookmarks: [],
                        id: "1",
                      },
                    ],
                    following: [],
                    bookmarks: [],
                    id: "2",
                  },
                ],
                following: [
                  {
                    _id: "asassddsd243434",
                    firstName: "Jignesh",
                    lastName: "Ghosh",
                    username: "jiggighosh@gmail.com",
                    password: "1234abcd",
                    createdAt: "2022-03-21T10:12:12+05:30",
                    updatedAt: "2022-05-14T18:10:33+05:30",
                    userHandler: "jiggi",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                    link: "https://jiggi.netlify.app",
                    bio: "Social Media Influencer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "2",
                  },
                  {
                    _id: "asassddfdsfdgsd32323",
                    firstName: "Jyoti",
                    lastName: "Kashti",
                    username: "jyotikashti@gmail.com",
                    password: "1234asdf",
                    createdAt: "2022-05-12T08:30:12+05:30",
                    updatedAt: "2022-05-14T18:11:48+05:30",
                    userHandler: "jyotiKashti",
                    pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/uchicha_crest_ngetfr.jpg",
                    link: "https://jyotikashti.netlify.app",
                    bio: "Web Designer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "3",
                  },
                ],
                bookmarks: [],
                id: "1",
              },
            ],
            bookmarks: [],
            id: "3",
          },
        ],
        bookmarks: [],
        id: "2",
      },
    ],
    bookmarks: [],
    id: "4",
  },
  {
    _id: "asassddfd232fg23ssfdf",
    firstName: "Mohak",
    lastName: "Seth",
    username: "seth.mohak@gmail.com",
    password: "1234asdf",
    createdAt: "2022-02-10T09:30:12+05:30",
    updatedAt: "2022-05-17T10:24:04+05:30",
    userHandler: "seth.mohak",
    pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650022195/one_piece_2_jcjkvz.jpg",
    link: "https://seth.mohak.netlify.app",
    bio: "Mobile Developer",
    followers: [
      {
        _id: "asassddsd243434",
        firstName: "Jignesh",
        lastName: "Ghosh",
        username: "jiggighosh@gmail.com",
        password: "1234abcd",
        createdAt: "2022-03-21T10:12:12+05:30",
        updatedAt: "2022-05-16T18:13:22+05:30",
        userHandler: "jiggi",
        pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
        link: "https://jiggi.netlify.app",
        bio: "Social Media Influencer",
        followers: [
          {
            _id: "asassdafdgdk",
            firstName: "Chetan",
            lastName: "Patel",
            username: "chetan@gmail.com",
            password: "1234abcd",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-14T18:08:40+05:30",
            userHandler: "chetan",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
            link: "https://chetanspage.netlify.app",
            bio: "Aspiring Software Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "1",
          },
        ],
        following: [
          {
            _id: "asassdafdgdk",
            firstName: "Chetan",
            lastName: "Patel",
            username: "chetan@gmail.com",
            password: "1234abcd",
            createdAt: "2022-01-25T10:38:12+05:30",
            updatedAt: "2022-05-16T18:11:33+05:30",
            userHandler: "chetan",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
            link: "https://chetanspage.netlify.app",
            bio: "Aspiring Software Developer",
            followers: [],
            following: [
              {
                _id: "asassddsd243434",
                firstName: "Jignesh",
                lastName: "Ghosh",
                username: "jiggighosh@gmail.com",
                password: "1234abcd",
                createdAt: "2022-03-21T10:12:12+05:30",
                updatedAt: "2022-05-14T18:10:33+05:30",
                userHandler: "jiggi",
                pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                link: "https://jiggi.netlify.app",
                bio: "Social Media Influencer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "2",
              },
              {
                _id: "asassddfdsfdgsd32323",
                firstName: "Jyoti",
                lastName: "Kashti",
                username: "jyotikashti@gmail.com",
                password: "1234asdf",
                createdAt: "2022-05-12T08:30:12+05:30",
                updatedAt: "2022-05-14T18:11:48+05:30",
                userHandler: "jyotiKashti",
                pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/uchicha_crest_ngetfr.jpg",
                link: "https://jyotikashti.netlify.app",
                bio: "Web Designer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "3",
              },
            ],
            bookmarks: [],
            id: "1",
          },
          {
            _id: "asassddfd232fgfg323",
            firstName: "Vijay",
            lastName: "Kamle",
            username: "vijaykamle@gmail.com",
            password: "1234asdf",
            createdAt: "2022-04-09T09:30:12+05:30",
            updatedAt: "2022-05-14T18:12:29+05:30",
            userHandler: "subhashdugar",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650022195/saitama_isaxm6.jpg",
            link: "https://subhasdugar.netlify.app",
            bio: "Web Developer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "4",
          },
        ],
        bookmarks: [],
        id: "2",
      },
    ],
    following: [],
    bookmarks: [],
    id: "5",
  },
  {
    _id: "asassddfasadsdgfssfdf",
    firstName: "Karthik",
    lastName: "Bandi",
    username: "karthikbandi@gmail.com",
    password: "1234asdf09",
    createdAt: "2022-02-17T09:30:12+05:30",
    updatedAt: "2022-05-17T10:33:36+05:30",
    userHandler: "karthikbandi",
    pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/rinnegan_1_uyflkv.jpg",
    link: "https://karthikbandi.netlify.app",
    bio: "SDE-1 at Google",
    followers: [
      {
        _id: "asassdafdgdk",
        firstName: "Chetan",
        lastName: "Patel",
        username: "chetan@gmail.com",
        password: "1234abcd",
        createdAt: "2022-01-25T10:38:12+05:30",
        updatedAt: "2022-05-16T18:14:29+05:30",
        userHandler: "chetan",
        pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
        link: "https://chetanspage.netlify.app",
        bio: "Aspiring Software Developer",
        followers: [
          {
            _id: "asassddsd243434",
            firstName: "Jignesh",
            lastName: "Ghosh",
            username: "jiggighosh@gmail.com",
            password: "1234abcd",
            createdAt: "2022-03-21T10:12:12+05:30",
            updatedAt: "2022-05-16T18:11:07+05:30",
            userHandler: "jiggi",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
            link: "https://jiggi.netlify.app",
            bio: "Social Media Influencer",
            followers: [
              {
                _id: "asassdafdgdk",
                firstName: "Chetan",
                lastName: "Patel",
                username: "chetan@gmail.com",
                password: "1234abcd",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-14T18:08:40+05:30",
                userHandler: "chetan",
                pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
                link: "https://chetanspage.netlify.app",
                bio: "Aspiring Software Developer",
                followers: [],
                following: [],
                bookmarks: [],
                id: "1",
              },
            ],
            following: [],
            bookmarks: [],
            id: "2",
          },
          {
            _id: "asassddfdsfdgsd32323",
            firstName: "Jyoti",
            lastName: "Kashti",
            username: "jyotikashti@gmail.com",
            password: "1234asdf",
            createdAt: "2022-05-12T08:30:12+05:30",
            updatedAt: "2022-05-16T18:11:32+05:30",
            userHandler: "jyotiKashti",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/uchicha_crest_ngetfr.jpg",
            link: "https://jyotikashti.netlify.app",
            bio: "Web Designer",
            followers: [
              {
                _id: "asassdafdgdk",
                firstName: "Chetan",
                lastName: "Patel",
                username: "chetan@gmail.com",
                password: "1234abcd",
                createdAt: "2022-01-25T10:38:12+05:30",
                updatedAt: "2022-05-16T18:11:07+05:30",
                userHandler: "chetan",
                pic: "https://res.cloudinary.com/randomwave45/image/upload/v1652600420/wp7674077_p8sijj.webp",
                link: "https://chetanspage.netlify.app",
                bio: "Aspiring Software Developer",
                followers: [],
                following: [
                  {
                    _id: "asassddsd243434",
                    firstName: "Jignesh",
                    lastName: "Ghosh",
                    username: "jiggighosh@gmail.com",
                    password: "1234abcd",
                    createdAt: "2022-03-21T10:12:12+05:30",
                    updatedAt: "2022-05-14T18:10:33+05:30",
                    userHandler: "jiggi",
                    pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
                    link: "https://jiggi.netlify.app",
                    bio: "Social Media Influencer",
                    followers: [],
                    following: [],
                    bookmarks: [],
                    id: "2",
                  },
                ],
                bookmarks: [],
                id: "1",
              },
            ],
            following: [],
            bookmarks: [],
            id: "3",
          },
        ],
        following: [
          {
            _id: "asassddsd243434",
            firstName: "Jignesh",
            lastName: "Ghosh",
            username: "jiggighosh@gmail.com",
            password: "1234abcd",
            createdAt: "2022-03-21T10:12:12+05:30",
            updatedAt: "2022-05-14T18:10:33+05:30",
            userHandler: "jiggi",
            pic: "https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg",
            link: "https://jiggi.netlify.app",
            bio: "Social Media Influencer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "2",
          },
          {
            _id: "asassddfdsfdgsd32323",
            firstName: "Jyoti",
            lastName: "Kashti",
            username: "jyotikashti@gmail.com",
            password: "1234asdf",
            createdAt: "2022-05-12T08:30:12+05:30",
            updatedAt: "2022-05-14T18:11:48+05:30",
            userHandler: "jyotiKashti",
            pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/uchicha_crest_ngetfr.jpg",
            link: "https://jyotikashti.netlify.app",
            bio: "Web Designer",
            followers: [],
            following: [],
            bookmarks: [],
            id: "3",
          },
        ],
        bookmarks: [],
        id: "1",
      },
    ],
    following: [],
    bookmarks: [],
    id: "6",
  },
  {
    _id: "asassddfd23dgdg334df",
    firstName: "Sarita",
    lastName: "Chandra",
    username: "sarithachandra@gmail.com",
    password: "1234asdf09",
    createdAt: "2022-03-19T09:30:12+05:30",
    updatedAt: "2022-05-16T18:11:01+05:30",
    userHandler: "saritachandra",
    pic: "https://res.cloudinary.com/randomwave45/image/upload/v1650009611/rinnegan_2_w9ytuk.jpg",
    link: "https://sarithachandra.netlify.app",
    bio: "SDE-1 at Invact",
    followers: [],
    following: [],
    bookmarks: [],
    id: "7",
  },
  {
    _id: "fdgdg5590sd90",
    firstName: "Aashita",
    lastName: "Jha",
    username: "aashitajha@gmail.com",
    password: "1234asdf",
    createdAt: "2022-03-20T09:30:12+05:30",
    updatedAt: "2022-05-16T18:11:01+05:30",
    userHandler: "aashitajha",
    pic: "https://res.cloudinary.com/randomwave45/image/upload/v1647440368/sample.jpg",
    link: "https://aashitajha.netlify.app",
    bio: "SDE-II at Invact",
    followers: [],
    following: [],
    bookmarks: [],
    id: "8",
  },
];
